import numpy as np
import matplotlib.pyplot as plt
def plotter(var_list, means2, stds2, true_names, sl, color):
    vars = var_list
    means = []
    stds = []
    super_labels = []
    for var in vars:
        means.append(float(means2[var]))
        stds.append(float(stds2[var]))
        if sl == "y":
            super_labels.append(true_names[var])
    #print(means)
    #print(stds)
    ind = np.arange(len(vars))
    width = 0.5

    fig, ax = plt.subplots()
    rects = ax.bar(ind, means, width, yerr=stds, color=color, label='Vars')

    ax.set_ylabel("Single Input Activation Score (Likely Cost Correlate)")
    ax.set_title("NN Computed Variable Values")
    ax.set_xticks(ind)
    if sl == "y":
        ax.set_xticklabels(super_labels)
    else:
        ax.set_xticklabels(vars)
    #ax.legend()
    plt.show()

def var_true_names():
    true_var_dict = {
        "TB":"Building Tag",
        "TSP":"Space Tag",
        "TSC":"Science Tag",
        "TPL":"Plant Tag",
        "TM":"Microbe Tag",
        "TA":"Animal Tag",
        "TPO":"Power Tag",
        "TJ":"Jovian Tag",
        "TEA":"Earth Tag",
        "TC":"City Tag",
        "TEV":"Event Tag",
        "TV":"Venus Tag",
        "TW":"Wild Tag",
        "ROXX4":"Requires Max Oxygen 4%",
        "ROXX5":"Requires Max Oxygen 5%",
        "ROXX6":"Requires Max Oxygen 6%",
        "ROXX7":"Requires Max Oxygen 7%",
        "ROXX8":"Requires Max Oxygen 8%",
        "ROXN2":"Requires Min Oxygen 2%",
        "ROXN3":"Requires Min Oxygen 3%",
        "ROXN4":"Requires Min Oxygen 4%",
        "ROXN5":"Requires Min Oxygen 5%",
        "ROXN6":"Requires Min Oxygen 6%",
        "ROXN7":"Requires Min Oxygen 7%",
        "ROXN8":"Requires Min Oxygen 8%",
        "ROXN9":"Requires Min Oxygen 9%",
        "ROXN11":"Requires Min Oxygen 11%",
        "ROXN12":"Requires Min Oxygen 12%",
        "ROXN13":"Requires Min Oxygen 13%",
        "ROCX3":"Requires Max Oceans 3",
        "ROCN2":"Requires Min Oceans 2",
        "ROCN3":"Requires Min Oceans 3",
        "ROCN4":"Requires Min Oceans 4",
        "ROCN5":"Requires Min Oceans 5",
        "ROCN6":"Requires Min Oceans 6",
        "ROCN8":"Requires Min Oceans 8",
        "RTEXN20":"Requires Max Temperature -20C",
        "RTEXN18":"Requires Max Temperature -18C",
        "RTEXN14":"Requires Max Temperature -14C",
        "RTEXN12":"Requires Max Temperature -12C",
        "RTEXN10":"Requires Max Temperature -10C",
        "RTENN24":"Requires Min Temperature -24C",
        "RTENN20":"Requires Min Temperature -20C",
        "RTENN16":"Requires Min Temperature -16C",
        "RTENN14":"Requires Min Temperature -14C",
        "RTENN12":"Requires Min Temperature -12C",
        "RTENN10":"Requires Min Temperature -10C",
        "RTENN8":"Requires Min Temperature -8C",
        "RTENN6":"Requires Min Temperature -6C",
        "RTENN4":"Requires Min Temperature -4C",
        "RTEN0":"Requires Min Temperature 0C",
        "RTEN2":"Requires Min Temperature 2C",
        "RTEN4":"Requires Min Temperature 4C",
        "RVX10":"Requires Max Venus 10%",
        "RVX14":"Requires Max Venus 14%",
        "RVN6":"Requires Min Venus 6%",
        "RVN8":"Requires Min Venus 8%",
        "RVN10":"Requires Min Venus 10%",
        "RVN12":"Requires Min Venus 12%",
        "RVN16":"Requires Min Venus 16%",
        "RVN18":"Requires Min Venus 18%",
        "RPRT":"Requires Titanium Production",
        "RTSC2":"Requires 2 Science Tags",
        "RTSC3":"Requires 3 Science Tage",
        "RTSC4":"Requires 4 Science Tags",
        "RTSC5":"Requires 5 Science Tags",
        "RTSC7":"Requires 7 Science Tags",
        "RTJ":"Requires 1 Jovian Tag",
        "RTJ2":"Requires 2 Jovian Tags",
        "RTPO2":"Requires 2 Power Tags",
        "RTP1":"Requires 1 Plant Tag",
        "RTM":"Requires 1 Microbe Tag",
        "RTA":"Requires 1 Animal Tag",
        "RPRS":"Requires a Steel Production",
        "RG":"Requires a Greenery Tile",
        "RC":"Requires a city in play",
        "RC2":"Requires 2 cities in play",
        "REM":"Megacredits",
        "RES":"Steel",
        "RET":"Titanium",
        "REP":"Plants",
        "REE":"Energy",
        "REH":"Heat",
        "REA":"Animals",
        "REMI":"Microbes",
        "REF":"Floaters",
        "REMA":"Anyone's Megacredits",
        "RESA":"Anyone's Steel",
        "RETA":"Anyone's Titanium",
        "REPA":"Anyone's Plants",
        "REEA":"Anyone's Energy",
        "REHA":"Anyone's Heat",
        "REAA":"Anyone's Animals",
        "PRM":"Production of your Megacredits",
        "PRS":"Production of your Steel",
        "PRT":"Production of your Titanium",
        "PRP":"Production of your Plants",
        "PRE":"Production of your Energy",
        "PRH":"Production of your Heat",
        "PRMA":"Production of anyone's Megacredits",
        "PRSA":"Production of anyone's Steel",
        "PRTA":"Production of anyone's Titanium",
        "PRPA":"Production of anyone's Plants",
        "PREA":"Production of anyone's Energy",
        "PRHA":"Production of anyone's Heat",
        "DA1":"Discount of 1 on any card",
        "DA2":"Discount of 2 on any card",
        "DSP2":"Discount of 2 on space cards",
        "DSP4":"Discount of 4 on space cards",
        "DEA3":"Discount of 3 on Earth cards",
        "DV2":"Discount of 2 on Venus cards",
        "GOX":"Raise oxygen by one step",
        "GTE":"Raise temperature by one step",
        "GV":"Raise Venus by one step",
        "GTR":"Raise Terraform Rating by one step",
        "PLC":"Place a City Tile",
        "PLCRO":"Place the Research Outpot City",
        "PLCZ":"Place a City where it will be worth Zero Points (reserved space)",
        "PLOC":"Place an Ocean",
        "PLG":"Place a Greenery",
        "PLT":"Place a Tile",
        "PLTA":"Place a Tile Adjacent",
        "PLCO":"Place a Colony",
        "PLCOO":"Place a colony anywhere",
        "SA":"One Animal",
        "SAA":"Anyone's Animnal",
        "SM":"One Microbe",
        "SMO":"One microbe other / any card",
        "SMA":"Anyone's microbe",
        "SMTR2":"Gain 1 TR for spending 2 Microbe",
        "SMTR3":"Gain 1 TR for spending 3 Microbe",
        "SF":"Floater",
        "SFO":"Floater other/any card",
        "SFV":"Floater Venus Card",
        "SFTR2":"Gain 1 TR for spending 2 floaters",
        "PO":"Flat Points",
        "POSC2":"Points per 2 Science Resources",
        "POM025":".25 points per Microbe Resource",
        "POM033":".33 points per Microbe Resource",
        "POM05":".50 points per Microbe Resource",
        "POA05":".50 points per Animal Resource",
        "POA1":"1 point per Animal Resource",
        "POF033":".33 points per Floater Resource",
        "POF05":".50 points per Floater Resource",
        "POO1":"1 point per adjacent ocean resource",
        "POC1":"1 point per adjacent city",
        "POJ1":"1 point per Jovian Tag",
        "D":"Default cost (estimated draft cost)",
        "CD":"Card Draw",
        "CDPT":"Card Draw Per Turn",
        "INV":"Invent, draw top card and buy or discard",
        "SFL":"Search for life action",
        "MRS":"Martian Rails Action",
        "WIE":"Water Import from Europa Action",
        "SPE":"Space Elevator Action",
        "DVC":"Development Center Action",
        "EQM":"Equatorial Magnetizer Action",
        "ARA":"Arctic Algae Effect",
        "SCF":"Security Fleet",
        "OPA":"Optimal Aerobraking",
        "RVC":"Rover Construction",
        "MRR":"Miranda Resort",
        "LNC":"Land Claim",
        "ELC":"Electro Catapult",
        "ADA":"Advanced Alloys",
        "MSU":"Mars University",
        "VEN":"Viral Enhancers",
        "SPM":"Space Mirrors",
        "RBW":"Robotic Workforce",
        "PYC":"Physics Complex",
        "GHS":"Greenhouses",
        "TLS":"Toll Station",
        "INW":"Ironworks",
        "PWG":"PowerGrid",
        "STW":"Steelworks",
        "ORP":"Ore Processor",
        "MDA":"Media Archives",
        "MDG":"Media Group",
        "BNC":"Business Contacts",
        "IDC":"Industrial Center",
        "ECZ":"Ecological Zone",
        "ZPN":"Zeppelin",
        "WRM":"Worms",
        "DCP":"Decomposers",
        "CRT":"Cartels",
        "HBV":"Herbivores",
        "INS":"Insects",
        "CEO":"CEO",
        "ISN":"Insulation",
        "ATT":"Adaptation Technology",
        "CTC":"Caretaker Contract",
        "STD":"Standard Technology",
        "PET":"Pets",
        "PTH":"Protected Habitats",
        "SAT":"Satellites",
        "WSP":"Water Splitting Plant",
        "OCL":"Olympus Conference",
        "AQP":"Aquifer Pumping",
        "ENG":"Energy Saving",
        "IVC":"Invention Contest",
        "PIF":"Power Infrastructure"
    }
    return true_var_dict
